### ISSUE TITLE
Open Graph Protocol/Twitter Cards issues

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Maps4HTML-Workshop-2020#45]
At least two issues with the [OGP](https://ogp.me)/[Twitter cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) markup:

- Missing `og:image:alt` and `twitter:image:alt` to provide alternative text for images.
- Invalid image URLs - they **should** be absolute URLs, this isn't well documented but see this [SO post](https://stackoverflow.com/questions/9858577/open-graph-can-resolve-relative-url) and also the "Link preview" from Facebook's [Sharing debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.w3.org%2F2020%2Fmaps%2F) in the screen shot below doesn't display an image.

![ogp-web-maps](https://user-images.githubusercontent.com/26493779/79592939-064b1b00-80db-11ea-9f0f-d485e85c563f.png)

**Comment by AmeliaBR** [comment]
Thanks for running those checks. (They were part of the to-do's that never got done for #20)

Now that we have a canonical URL to reference, should be able to make these absolute.

I can't recall now whether I left the `alt` off intentionally because I couldn't think of a useful description, or whether I just copied the markup from a sloppy example & didn't realize they were missing.

With the updated wordmark, I should definitely add an alt for the large image suggested for OpenGraph:

“Maps for the Web, Sept−Oct 2020 #Maps4HTML”
![Those words, plus the logo](https://www.w3.org/2020/maps/assets/media/wordmark/logo_horizontal_blue_fb_1200x630.png)

For the smaller logo I'm using for Twitter, I'm not sure an alt is useful, though.
![The logo, a compass rose made of cursor pointers](https://www.w3.org/2020/maps/assets/media/icon/icon_blue_288x288.png)

But now that I'm looking at page source code, I see I missed updating a few page descriptions which still refer to Montreal… going to fix that now.

**Comment by AmeliaBR** [comment]
Made the fixes above & Twitter validator renders as expected (once I changed my account settings to turn off data saver mode temporarily, anyway…), but Facebook gave a new warning:

> The provided 'og:image' properties are not yet available because new images are processed asynchronously. To ensure shares of new URLs include an image, specify the dimensions using 'og:image:width' and 'og:image:height' tags.

So that's new, but probably good for users.

**Comment by AmeliaBR** [comment]
OK, looking good!

![Screenshot of the Facebook link preview for the Workshop Minutes & Report page](https://user-images.githubusercontent.com/9876129/79597543-aedb8980-809f-11ea-977c-f10a79994028.png)

The  Facebook debugger warnings still say I should add tags for “og:url, og:title, og:description, fb:app_id”, but since it quite successfully infers the first three from the standard HTML markup & I have no use for the app ID (it's for accessing [Facebook analytics](https://developers.facebook.com/docs/sharing/webmasters#basic)), I think we're OK to close this off.

Thanks as always, @Malvoz, for being the QA team!
