### ISSUE TITLE
Presenter and panel schedule negotiations and requirements

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML-Workshop-2020#68]
Terence Eden is currently scheduled for 4 am local time - no can do.
Nicolò Carpignoli needs to be scheduled for between 8:00 UTC to 18:00 UTC
Add Joshua Lieberman as co-presenter with Christine Perey.
Karel Charvat can't present on Sept 27 or Sept 28, as these are Czech holidays.
Thijs Brentjens' presentation is at midnight his time, not ideal but acceptable. Noting here for discussion at least, if not doing something about it for him.

Will update this issue as more emails arrive...

**Comment by AmeliaBR** [comment]
The “Creating accessible Web map widgets” is too late in the day for one of the panelists, before 21:00 UTC is preferred.

**Comment by AmeliaBR** [comment]
Other issue: Gethin Rees' topic was original proposed as a demo, not a talk. Need to confirm the time expectation.

**Comment by AmeliaBR** [comment]
Converting the constraints to Days

- Terence Eden (authoring use cases): Day 2, 3, 4 -- Week 2 Day 4 (but 11pm his time)
- Nicolò Carpignoli (accessibility / research questions): Day 2, Day 3  --- Week 2, Day 2
- Widget Accessibility Panel: Day 2, Day 3  --- Week 2, Day 2
- Karel Charvat (formats / composing maps) -- Week 2 Day 3,
- Thijs Brentjens - Move to Week 1, Day 3, group with internationalization theme

**Comment by prushforth** [comment]
> Other issue: Gethin Rees' topic was original proposed as a demo, not a talk. Need to confirm the time expectation.

Gethin Rees is on leave until Sept 1st., but he received email confirming him as a breakout leader, at least.  Let's go with it, it's what he proposed.

**Comment by AmeliaBR** [comment]
OK,  merged in changes for the issues identified so far. Commit message has a more readable description of what's changed, based on my rough notes above. Also had to move Karel Charvat's breakout session. 

In order to balance daily schedules, I've moved Peter's breakout session one day later.

I've moved Terence Eden to the Day 4 slot pending confirmation.

Also, @nchan0154 pointed out that her slot is very early in Hong Kong: she's OK pre-recording her talk, but I suggested we could move her talk with the other accessibility talks & panel on Week 2, Day 2.

If we do that, I'm not sure if we want to move Brandon Bigg's talk to a different day (maybe even Day 1?), and just have Week 1, Day 4 be two consecutive demo sessions?
